
export const ARCH_PROMPTS = [
    "A minimalist villa carved into a cliffside, overlooking the ocean, sharp geometric lines, concrete, glass, and teak wood, golden hour lighting, photorealistic, 8k.",
    "A futuristic bio-luminescent skyscraper in a dense cyberpunk city, intricate neon signage in Vietnamese, rainy night, Blade Runner aesthetic, ultra-detailed.",
    "A traditional Japanese pagoda nestled in a misty bamboo forest, serene atmosphere, gentle morning light filtering through the leaves, highly detailed woodwork.",
    "A deconstructivist museum with fragmented, dynamic forms, titanium cladding and glass shards, Zaha Hadid style, dramatic shadows, architectural photography.",
    "A Scandinavian-inspired A-frame cabin deep in a snowy pine forest, warm light glowing from within, cozy and isolated, hyperrealistic.",
    "A brutalist government building with massive, raw concrete forms, imposing scale, overcast sky, powerful and monolithic, fine art photography.",
    "A Victorian Gothic mansion, ornate spires and gargoyles, shrouded in fog on a moonlit night, mysterious and atmospheric.",
    "A sun-drenched Mediterranean villa with whitewashed walls, terracotta roof tiles, and vibrant bougainvillea, overlooking the Aegean Sea.",
    "An Art Deco skyscraper lobby, polished marble floors, geometric brass inlays, and lavish chandeliers, glamorous 1930s New York style.",
    "A treehouse complex interconnected by rope bridges, integrated seamlessly with the forest canopy, fantasy architecture, magical lighting.",
    "A desert shelter inspired by a scorpion's exoskeleton, biomimicry, sand-colored composite materials, harsh midday sun.",
    "An underwater research facility with large bubble windows looking out into a coral reef, schools of fish swimming by, serene and futuristic.",
    "A classic Haussmann-style apartment building in Paris, wrought-iron balconies, mansard roof, romantic evening light.",
    "A modern glass house in the middle of a dense forest, blurring the lines between indoors and outdoors, minimalist interior, tranquil.",
    "A converted industrial warehouse into a modern home, preserving exposed brick, steel beams, and large factory windows.",
    "A cliffside monastery in the Himalayas, traditional Tibetan architecture, prayer flags fluttering in the wind, majestic mountain backdrop.",
    "A floating city with interconnected platforms, futuristic watercraft, and vertical gardens, utopian sci-fi concept.",
    "A Spanish colonial hacienda with a central courtyard, fountain, and arched colonnades, warm, rustic, and inviting.",
    "An eco-futuristic dome structure covering a botanical garden, sustainable architecture, thriving with exotic plants.",
    "A Romanesque cathedral with massive stone walls, rounded arches, and intricate stained glass windows, awe-inspiring scale.",
    "A minimalist concrete house in the Icelandic highlands, set against a stark volcanic landscape, geothermal steam rising.",
    "A geode-inspired house, crystalline structures growing from the earth, iridescent and otherworldly.",
    "A traditional Vietnamese stilt house (nhà sàn) by a peaceful river, lush tropical surroundings, tranquil morning scene.",
    "A Bauhaus school building, functionalist design, primary colors, steel-frame construction, and glass curtain walls.",
    "A luxury safari lodge with thatched roofs and canvas walls, overlooking the African savanna at sunset.",
    "A whimsical fairytale castle with twisting towers, candy-colored details, and a sparkling moat.",
    "A research outpost on Mars, modular and pragmatic design, set against the red Martian landscape, sci-fi realism.",
    "An Islamic mosque with a grand dome, intricate geometric tilework (zellige), and a peaceful courtyard with fountains.",
    "A postmodern office building, playful mix of historical styles and bold colors, unconventional shapes.",
    "A rustic Italian farmhouse in Tuscany, stone walls, cypress trees, and rolling hills, warm afternoon light.",
    "A sleek, contemporary art gallery, white walls, polished concrete floors, and dramatic track lighting.",
    "A mobile, transforming tiny home, unfolds to reveal a larger living space, innovative and compact design.",
    "A Streamline Moderne diner, chrome details, curved lines, and neon signs, nostalgic 1950s Americana.",
    "A Shaker community building, profound simplicity, clean lines, and masterful, unadorned craftsmanship.",
    "An ancient, vine-covered temple ruin in a dense jungle, reminiscent of Angkor Wat, sense of discovery and history.",
    "A modernist beach house on stilts, panoramic ocean views, floor-to-ceiling glass, minimalist and elegant.",
    "A traditional Dutch canal house with a gabled facade, located in Amsterdam, reflected in the water.",
    "A high-tech data center, rows of glowing servers, cool blue lighting, complex network of cables, futuristic and clean.",
    "An igloo-inspired hotel under the Northern Lights, glowing from within, magical and serene arctic scene.",
    "A Greek amphitheater carved into a hillside, ancient stone, overlooking a dramatic landscape at dusk.",
    "A timber-framed house with wattle and daub walls, thatched roof, charming medieval English countryside style.",
    "A Swiss chalet-style hotel in the Alps, intricate woodwork, flower boxes, surrounded by snow-capped mountains.",
    "A lighthouse on a rocky, storm-battered coast, waves crashing against the cliffs, dramatic and resilient.",
    "A colonial-era Vietnamese villa in Hanoi, yellow ochre walls, green shutters, and a mix of French and local architectural elements.",
    "A sustainable earthship home, built with recycled materials and integrated into the landscape, off-grid and eco-friendly.",
    "A grand opera house with a baroque facade, gilded interiors, and plush red velvet seats, opulent and cultural.",
    "A futuristic spaceport terminal, sleek transport ships docking, bustling with diverse alien species, epic sci-fi.",
    "A tranquil Zen garden with a teahouse, raked sand, moss-covered stones, and a single maple tree, embodying peace and simplicity.",
    "A vibrant, colorful favela on a hillside in Rio de Janeiro, labyrinthine alleys, a sense of community and life.",
    "A neolithic stone circle, like Stonehenge, aligned with the solstice sun, ancient and mystical.",
    "A glass-bottomed skywalk extending over a massive canyon, thrilling perspective, sense of height and awe.",
    "An abandoned Art Nouveau metro station entrance in Paris, ornate ironwork in the shape of plants, reclaimed by nature.",
    "A contemporary library with a massive, sweeping atrium and bookshelves lining the walls up to the ceiling.",
    "A nomadic yurt on the Mongolian steppe, star-filled night sky, a single campfire burning, sense of vastness.",
    "An Indian stepwell, intricate geometric patterns of stairs descending into the earth, architectural marvel.",
    "A log cabin built on the edge of a crystal-clear alpine lake, perfect reflection in the water, peaceful and idyllic.",
    "A solarpunk city with buildings covered in vegetation and integrated wind turbines, optimistic and green future.",
    "A fortified medieval castle with a moat, drawbridge, and high stone walls, historical and formidable.",
    "A classic American barn, red paint, white trim, set in a field of golden wheat, rustic and iconic.",
    "A hidden cove with pirate shipwrecks and a village built into the cliffs, adventurous and mysterious.",
    "A sleek monorail train station in a futuristic city, trains gliding silently on elevated tracks.",
    "A Roman villa with an open-air atrium, mosaic floors, and frescoes on the walls, historical luxury.",
    "An Egyptian temple complex, massive pylons carved with hieroglyphs, avenue of sphinxes, ancient and grand.",
    "A geodesic dome home in a Joshua Tree desert landscape, connecting with nature, bohemian and modern.",
    "A Russian Orthodox church with colorful onion domes, set in a snowy landscape, intricate and iconic.",
    "A colonial mansion in the American South, grand columns, sweeping verandas, and oak trees draped in Spanish moss.",
    "A research station perched on the edge of an active volcano, glowing lava visible, dramatic and scientific.",
    "A cliff-dwelling city carved into a sandstone canyon, Anasazi-style architecture, historical and integrated with nature.",
    "A whimsical, oversized mushroom house in an enchanted forest, home to magical creatures.",
    "A state-of-the-art sports stadium with a retractable roof and a massive video screen, dynamic and energetic.",
    "A tranquil onsen (Japanese hot spring) bathhouse, hinoki wood tubs, steam rising, minimalist and relaxing.",
    "A brownstone apartment building in Brooklyn, iconic stoops, tree-lined street, charming and urban.",
    "A Persian palace courtyard with intricate tilework, reflecting pools, and fragrant gardens, historical elegance.",
    "A lighthouse keeper's cottage, quaint and weathered, perched on a small island.",
    "A steampunk city with brass clockwork mechanisms, airships floating overhead, and buildings powered by steam.",
    "A university campus with Gothic revival architecture, ivy-covered walls, and scholarly atmosphere.",
    "A salt flat hotel, built entirely of salt blocks, reflecting the vast, white landscape of Salar de Uyuni.",
    "A minimalist chapel made of light and concrete, Tadao Ando style, creating a spiritual and contemplative space.",
    "A high-speed hyperloop tunnel, futuristic pods traveling through a translucent tube, concept of future travel.",
    "A coastal village in Italy, colorful houses clinging to cliffs, like the Cinque Terre, picturesque and vibrant.",
    "A grand, historic railway station, vaulted glass ceilings, ornate clocks, and the bustle of travelers.",
    "A tropical resort with overwater bungalows, thatched roofs, and turquoise water, luxurious and idyllic.",
    "A hidden library in a cave, ancient scrolls and books lining the stone walls, illuminated by magical light.",
    "A modern winery with a tasting room overlooking vineyards, architecture that blends with the landscape.",
    "An Aztec pyramid, steep stone steps leading to a temple, set in a dense jungle, historical and imposing.",
    "A vibrant marketplace in Morocco, bustling with people, colorful spices, and intricate textiles.",
    "A bird-watching tower made of wood and steel, rising above the forest canopy, offering panoramic views.",
    "A classic American firehouse, red brick, large garage doors, and a brass fire pole, iconic and nostalgic.",
    "A futuristic vertical farm, layers of hydroponic plants glowing under artificial lights inside a skyscraper.",
    "An abandoned Cold War-era spy station on a snowy mountain peak, satellite dishes covered in ice, mysterious and eerie.",
    "A Tudor-style village, half-timbered houses, cobblestone streets, and a lively town square.",
    "A grand ballroom in a Venetian palace, Murano glass chandeliers, frescoed ceilings, and masked guests.",
    "A sunken city, ruins of ancient buildings visible beneath the clear ocean water, lost and enchanting.",
    "A contemporary concert hall with acoustically optimized, flowing wooden interior surfaces, architectural and auditory harmony.",
    "An artist's loft studio in SoHo, New York, large windows, high ceilings, paint-splattered floors, creative and messy.",
    "A sustainable, green-roofed office building that merges into a public park, biophilic design.",
    "A Viking longhouse with a turf roof, carved dragon heads, and a central hearth, historical and rugged.",
    "A retro-futuristic Googie architecture building, like a 1960s coffee shop, with upswept roofs and geometric shapes.",
    "A treetop restaurant, offering diners a view from within the branches of a giant, ancient tree.",
    "A peaceful Cistercian monastery with simple, unadorned stone architecture and a cloistered garden.",
    "A glass-walled elevator ascending the outside of a supertall skyscraper, offering breathtaking city views.",
    "A Pre-Raphaelite painter's studio, filled with exotic textiles, artifacts, and a half-finished masterpiece on the easel.",
    "A high-tech, automated greenhouse on a space station, growing food for astronauts in zero gravity."
];

export const INTERIOR_PROMPTS = [
    "A Japandi-style living room, minimalist furniture, natural light from a large window, neutral color palette with black accents, washi paper pendant light, serene and calm.",
    "An industrial loft kitchen with exposed brick walls, stainless steel countertops, open shelving with cast iron pots, Edison bulb lighting, urban and functional.",
    "A bohemian-style bedroom filled with plants, macrame wall hangings, rattan furniture, layered textiles with eclectic patterns, warm morning light, cozy and free-spirited.",
    "A mid-century modern dining room, iconic Eames chairs, a walnut wood table, a Sputnik chandelier, clean lines and organic shapes, sophisticated and timeless.",
    "A luxurious Art Deco bathroom, black and gold geometric tiles, a clawfoot tub, a sunburst mirror, opulent and glamorous.",
    "A rustic farmhouse living room, a large stone fireplace, exposed wooden ceiling beams, a comfy plaid sofa, warm and inviting atmosphere.",
    "A minimalist Scandinavian home office, light wood desk, ergonomic chair, well-organized with very few objects, bright and focused.",
    "A maximalist library, floor-to-ceiling bookshelves overflowing with books, a velvet chesterfield sofa, a Persian rug, a collection of curiosities, rich and layered.",
    "A coastal-style sunroom, white wicker furniture, blue and white striped cushions, panoramic windows overlooking the beach, airy and relaxing.",
    "A dark academia-themed study, dark wood paneling, a large mahogany desk, leather-bound books, a globe, and brass desk lamp, scholarly and moody.",
    "A futuristic minimalist apartment with integrated smart technology, seamless white surfaces, holographic displays, and furniture that morphs, clean and high-tech.",
    "A cozy English cottage kitchen, AGA stove, shaker cabinets in a muted green, a ceramic Belfast sink, and dried herbs hanging from the ceiling.",
    "A grand, double-height living room in a modern mansion, a massive contemporary chandelier, a floating staircase, and a glass wall overlooking a pool.",
    "A tranquil Zen meditation room, tatami mats on the floor, a single low table, shoji screen dividers, and a view of a small rock garden.",
    "A vibrant, colorful Moroccan riad living room, intricate tilework, plush floor cushions, a large brass tray table, and light filtering through a carved wood screen.",
    "A moody, speakeasy-style home bar, dark leather bar stools, a polished wood bar top, shelves of whiskey bottles, and dim, warm lighting.",
    "An eclectic artist's studio, large north-facing windows, paint-splattered floors, canvases leaning against the walls, a beautiful creative mess.",
    "A sleek, contemporary bedroom with a low-profile platform bed, integrated LED lighting in the headboard, and a neutral, monochromatic color scheme.",
    "A Shabby Chic living room, distressed white furniture, floral patterns, vintage finds, and a crystal chandelier, romantic and comfortable.",
    "An Indochine-style living space in Vietnam, dark lacquered wood furniture, patterned floor tiles, louvered shutters, and tropical plants, elegant and historical.",
    "A child's bedroom designed as a whimsical forest, a treehouse bed, walls painted with murals of animals, and soft, magical lighting.",
    "A high-tech home gym with smart fitness equipment, rubber flooring, full-length mirrors, and an energizing view.",
    "A grand ballroom with polished parquet floors, gilded wall moldings, massive crystal chandeliers, and floor-to-ceiling windows with velvet drapes.",
    "A cozy reading nook built into a bay window, a plush window seat with lots of cushions, and built-in bookshelves.",
    "A professional recording studio control room, large mixing console, sound-dampening panels on the walls, and a view into the live room.",
    "A biophilic-designed office space, a living wall covered in plants, natural wood desks, and lighting that mimics the sun's cycle.",
    "A French provincial dining room, a rustic farmhouse table, Louis XVI-style chairs with cane backs, and a delicate chandelier.",
    "A home theater with plush reclining chairs, a massive projector screen, acoustic wall panels, and a starry ceiling effect.",
    "A traditional Japanese tea room, simple and uncluttered, with a tatami mat floor and a low wooden table for the tea ceremony.",
    "A light-filled conservatory, glass walls and ceiling, filled with exotic potted plants and comfortable seating, a perfect indoor garden.",
    "A wabi-sabi inspired living room, celebrating imperfection, with handmade pottery, weathered wood, and a focus on natural, humble materials.",
    "A glamorous Hollywood Regency bedroom, mirrored furniture, a tufted velvet headboard, and bold, dramatic colors.",
    "A spacious, open-plan kitchen and living area in a barn conversion, with a vaulted ceiling and original timber frames.",
    "A serene, spa-like bathroom with a large walk-in shower, a freestanding stone tub, and natural materials like bamboo and river rocks.",
    "A quirky, retro-themed living room with 1970s colors (avocado green, orange), a sunken conversation pit, and a shag carpet.",
    "An elegant Neoclassical entryway, marble floors, classical columns, a grand staircase, and a bust on a pedestal.",
    "A basement converted into a cozy wine cellar, stone walls, wooden wine racks, and a small tasting table with leather chairs.",
    "A modern, minimalist kitchen with handleless cabinets, a seamless Corian countertop, and state-of-the-art appliances.",
    "A student's dormitory room, cleverly organized to maximize space, with a loft bed, a compact desk, and personal touches.",
    "A luxury walk-in closet, custom-built shelving for shoes and bags, an island with drawers, and perfect lighting.",
    "A traditional Chinese living room, carved rosewood furniture, silk cushions, and a large watercolor screen.",
    "An industrial-style bathroom with a concrete vanity, black metal fixtures, and a subway-tiled shower.",
    "A sun-drenched breakfast nook, a round table, a built-in bench with colorful pillows, perfect for a morning coffee.",
    "A home library with a rolling ladder to reach the top shelves, a comfortable leather armchair, and a fireplace.",
    "A Southwestern-style living room, a kiva fireplace, terracotta floor tiles, exposed wooden vigas, and Navajo textiles.",
    "A clean, contemporary laundry room, efficient front-loading machines, ample counter space for folding, and smart storage solutions.",
    "A tropical-themed bathroom with large-leaf patterned wallpaper, a bamboo vanity, and a shower that feels like a waterfall.",
    "A formal dining room in a Georgian house, mahogany furniture, a crystal chandelier, and silk wallpaper.",
    "A musician's practice room, soundproofed walls, guitars hanging on display, a drum kit, and an amplifier stack.",
    "A cozy attic bedroom with slanted ceilings, a skylight for stargazing, and exposed wood beams.",
    "A bright, cheerful kitchen with yellow cabinets, a patterned tile backsplash, and lots of natural light.",
    "A sophisticated gentleman's study with a Chesterfield sofa, a tartan armchair, and walls adorned with antique maps.",
    "A modern nursery with a neutral color palette, a stylish crib, and subtle, artistic decor.",
    "A large, open-concept artist loft with different zones for living, working, and sleeping, defined by furniture arrangement.",
    "A gothic-inspired dining room with a long, dark wood table, high-backed chairs, and wrought-iron candelabras.",
    "A beach house living room with slipcovered white sofas, driftwood accents, and shades of blue and sand.",
    "An Italian rustic kitchen with a long wooden table for family meals, a copper pot rack, and an open hearth.",
    "A serene bedroom with a palette of soft grays and blues, plush bedding, and blackout curtains for a restful sleep.",
    "A funky, pop art-inspired living room with bold colors, graphic art on the walls, and iconic plastic furniture.",
    "A high-end hotel suite living room with a stunning city view, luxurious fabrics, and elegant, contemporary furniture.",
    "A craftsman-style dining room with a built-in china cabinet, a sturdy oak table, and stained-glass light fixtures.",
    "A minimalist entryway with a simple console table, a large round mirror, and a single piece of art.",
    "A Victorian parlor with ornate furniture, heavy velvet curtains, a marble fireplace, and numerous houseplants.",
    "A modern kitchen with a large island that doubles as a breakfast bar, with sleek pendant lights hanging above.",
    "A teenager's bedroom with a gaming setup, LED strip lights, and posters of their favorite bands and games.",
    "A tranquil indoor pool area with natural stone tiles, lounge chairs, and large glass doors that open to a garden.",
    "A home office designed for productivity, with a large L-shaped desk, multiple monitors, and an ergonomic chair.",
    "A classic French bistro interior, small marble-topped tables, bentwood chairs, a zinc bar, and a chalkboard menu.",
    "A luxury master bathroom with a steam shower, a double vanity with vessel sinks, and heated floors.",
    "A cozy, cluttered writer's studio in an attic, books piled everywhere, a comfortable old armchair, and a vintage typewriter.",
    "A bright and modern dining area with a glass-topped table and colorful, transparent chairs.",
    "A traditional English drawing room with chintz sofas, an antique grandfather clock, and portraits on the walls.",
    "A contemporary living room with a low-slung modular sofa, a large abstract painting, and a sculptural coffee table.",
    "A rustic ski lodge common area with a massive stone fireplace, leather armchairs, and a view of the snowy mountains.",
    "A sleek, minimalist bathroom with a floating vanity, a wall-mounted toilet, and a seamless glass shower screen.",
    "A home recording booth, compact and acoustically treated, with a high-quality microphone and headphones.",
    "A cheerful playroom for kids, with colorful storage bins, a soft play mat, and a small table for arts and crafts.",
    "An elegant entryway with a black and white checkerboard marble floor and a sweeping staircase.",
    "A mid-century modern living room with a conversation pit, an Eames lounge chair, and a sunburst clock.",
    "A serene, all-white bedroom with different textures of fabrics to create warmth and interest.",
    "A kitchen pantry with floor-to-ceiling shelves, perfectly organized with glass jars and labeled baskets.",
    "A sophisticated living room with dark blue walls, brass accents, and a mix of velvet and leather furniture.",
    "A converted church interior, with stained glass windows casting colorful light, vaulted ceilings, and an open-plan living space.",
    "A solarium filled with tropical plants, a small fountain, and comfortable seating for relaxation.",
    "A minimalist bedroom where the bed is a simple mattress on a low wooden platform, creating a Zen-like atmosphere.",
    "A grand hotel lobby with a soaring atrium, multiple seating areas, and a spectacular central art installation.",
    "A compact and efficient tiny house interior, with multi-functional furniture and clever storage solutions.",
    "A classic American diner interior with red vinyl booths, a long counter with swivel stools, and a jukebox.",
    "A home greenhouse attached to the house, filled with tomato plants, herbs, and flowers, blurring the line between inside and out.",
    "An opulent master bedroom with a four-poster canopy bed, silk drapes, and a crystal chandelier.",
    "A contemporary Japanese bathroom with a deep soaking tub (ofuro), a wooden stool, and minimalist design.",
    "A vibrant kitchen with teal cabinets, a white subway tile backsplash, and brass hardware for a pop of color.",
    "A formal library with dark wood paneling, a fireplace, and comfortable leather armchairs for reading.",
    "A breezy, open-air living room in a tropical location, with no walls, just columns and a roof, surrounded by nature.",
    "A postmodern interior with playful shapes, bold colors, and a rejection of strict modernist rules.",
    "A cozy, Scandinavian-inspired nursery with a light wood crib, a soft sheepskin rug, and whimsical wall decals.",
    "An industrial-chic home office with a desk made from reclaimed wood and steel pipes, and a metal task lamp.",
    "A peaceful yoga and meditation space at home, with cork flooring, a small altar, and space for mats and props.",
    "A grand entryway with a double-height ceiling, a dramatic staircase, and a large statement chandelier.",
    "A charming breakfast room with a bay window, a built-in bench, and a view of a beautiful garden.",
    "A luxurious home spa with a sauna, a steam room, and a relaxation area with comfortable loungers.",
    "A masculine bedroom with a leather headboard, dark gray walls, and industrial-style furniture.",
    "A light and airy kitchen with white shaker cabinets, marble countertops, and a soft blue island.",
    "A traditional living room with a symmetrical furniture arrangement centered around a fireplace and a classic oriental rug.",
    "A modern, minimalist dining room with a concrete table, simple black chairs, and a single, dramatic pendant light."
];

export const ENHANCE_PROMPTS = {
  atmosphere: [
    "golden hour lighting",
    "rainy day",
    "night time",
    "dramatic shadows",
    "foggy morning",
    "sunset sky",
    "add snow",
    "overcast sky",
  ],
  materials: [
    "exposed brick walls",
    "polished concrete floor",
    "dark wood panels",
    "marble countertops",
    "brass fixtures",
    "terracotta tiles",
    "thatched roof",
  ],
  objects: [
    "add lush vegetation",
    "add a modern sofa",
    "remove people",
    "add a classic car",
    "add a sleeping cat",
    "more indoor plants",
    "a swimming pool",
  ],
  style: [
    "photorealistic, 8k",
    "cinematic look",
    "watercolor painting style",
    "vintage photo effect",
    "minimalist style",
    "cyberpunk aesthetic",
    "fantasy style",
  ],
};
